"""Kiểm thử bắt buộc của migration.

Test này chạy trên một DATABASE TẠM riêng, tạo và xoá hoàn toàn, để không
phá dữ liệu của các test khác.
"""

from __future__ import annotations

import uuid

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import make_url

from tests.conftest import alembic_config

pytestmark = pytest.mark.integration


@pytest.fixture(scope="module")
def temp_database(database_url: str) -> str:
    """Tạo một database tạm bằng chính quyền của database test.

    ⚠️  BẪY ĐÃ DÍNH: `str(URL)` của SQLAlchemy **che password thành `***`**.
    Dùng `str()` ở đây thì engine kết nối bằng password `***` và bị
    "password authentication failed". Lỗi này **chỉ lộ ra khi URL thật sự có
    password** (CI dùng service container có password), còn ở máy local đăng
    nhập kiểu trust thì không thấy gì — đúng dạng "phép đo thiếu một ca".
    Vì vậy phải dùng `render_as_string(hide_password=False)`.
    """
    url = make_url(database_url)
    name = f"vipphone_migration_{uuid.uuid4().hex[:10]}"

    admin = create_engine(url.set(database="postgres"), isolation_level="AUTOCOMMIT", future=True)
    with admin.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{name}"'))
    admin.dispose()

    temp_url = url.set(database=name).render_as_string(hide_password=False)
    try:
        yield temp_url
    finally:
        admin = create_engine(
            url.set(database="postgres"), isolation_level="AUTOCOMMIT", future=True
        )
        with admin.connect() as conn:
            conn.execute(
                text(
                    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                    "WHERE datname = :name AND pid <> pg_backend_pid()"
                ),
                {"name": name},
            )
            conn.execute(text(f'DROP DATABASE IF EXISTS "{name}"'))
        admin.dispose()


def test_upgrade_creates_expected_schema(temp_database: str):
    command.upgrade(alembic_config(temp_database), "head")

    engine = create_engine(temp_database, future=True)
    inspector = inspect(engine)

    tables = set(inspector.get_table_names())
    assert {"leads", "audit_events", "iphone_models", "alembic_version"} <= tables

    lead_columns = {col["name"] for col in inspector.get_columns("leads")}
    assert lead_columns == {
        "id",
        "lead_id",
        "gift_code",
        "full_name",
        "phone",
        "iphone_model",
        "iphone_year",
        "case_color",
        "company_name",
        "bni_chapter",
        "referrer_name",
        "source",
        "campaign",
        "utm_source",
        "utm_medium",
        "utm_campaign",
        "utm_content",
        "ref",
        "consent",
        "gift_status",
        "created_at",
        "updated_at",
        "redeemed_at",
        "redeemed_by",
    }

    index_names = {idx["name"] for idx in inspector.get_indexes("leads")}
    assert {
        "ix_leads_phone",
        "ix_leads_created_at",
        "ix_leads_gift_status",
        "ix_leads_dup",
        "uq_leads_active_duplicate",
    } <= index_names

    assert {idx["name"] for idx in inspector.get_indexes("audit_events")} >= {
        "ix_audit_events_gift_code_created",
        "ix_audit_events_lead_id",
        "ix_audit_events_created_at",
    }

    engine.dispose()


def test_migration_head_is_recorded(temp_database: str):
    command.upgrade(alembic_config(temp_database), "head")
    engine = create_engine(temp_database, future=True)
    with engine.connect() as conn:
        head = conn.execute(text("SELECT version_num FROM alembic_version")).scalar()
    engine.dispose()
    assert head == "0001_initial"


def test_seed_inserts_exactly_the_verified_models(temp_database: str):
    """Seed phải đúng 28 model đã có trong repo — KHÔNG tự bịa model mới."""
    command.upgrade(alembic_config(temp_database), "head")
    engine = create_engine(temp_database, future=True)
    with engine.connect() as conn:
        count = conn.execute(text("SELECT count(*) FROM iphone_models")).scalar()
        years = {row[0] for row in conn.execute(text("SELECT DISTINCT year FROM iphone_models"))}
        codes = [row[0] for row in conn.execute(text("SELECT model_code FROM iphone_models"))]
    engine.dispose()

    assert count == 28
    # 2025 và 2026 rỗng trong data/iphone-models.json nên KHÔNG được seed.
    assert years == {2018, 2019, 2020, 2021, 2022, 2023, 2024}
    assert len(set(codes)) == 28, "model_code phải duy nhất"


def test_partial_unique_index_enforces_duplicate_policy(temp_database: str):
    """Chính sách chống trùng phải được ÉP Ở TẦNG DATABASE."""
    command.upgrade(alembic_config(temp_database), "head")
    engine = create_engine(temp_database, future=True)

    insert = text(
        """
        INSERT INTO leads (lead_id, gift_code, full_name, phone, iphone_model,
                           iphone_year, case_color, consent, gift_status)
        VALUES (:lead_id, :gift_code, 'Khach', '0912345678', 'iPhone 16',
                2024, 'Đen', true, :status)
        """
    )

    with engine.begin() as conn:
        conn.execute(
            insert,
            {"lead_id": uuid.uuid4(), "gift_code": "VIP-26-AAAAAA", "status": "NEW"},
        )

    # Cùng phone + model + trạng thái còn hoạt động -> phải bị chặn.
    with pytest.raises(Exception) as excinfo:
        with engine.begin() as conn:
            conn.execute(
                insert,
                {
                    "lead_id": uuid.uuid4(),
                    "gift_code": "VIP-26-BBBBBB",
                    "status": "READY",
                },
            )
    assert "uq_leads_active_duplicate" in str(excinfo.value)

    # Huỷ bản ghi cũ rồi thì được phép tạo bản mới.
    with engine.begin() as conn:
        conn.execute(text("UPDATE leads SET gift_status = 'CANCELLED'"))
        conn.execute(
            insert,
            {"lead_id": uuid.uuid4(), "gift_code": "VIP-26-CCCCCC", "status": "NEW"},
        )

    engine.dispose()


def test_check_constraints_reject_bad_data(temp_database: str):
    command.upgrade(alembic_config(temp_database), "head")
    engine = create_engine(temp_database, future=True)

    base = {
        "lead_id": uuid.uuid4(),
        "gift_code": "VIP-26-DDDDDD",
    }
    sql = text(
        """
        INSERT INTO leads (lead_id, gift_code, full_name, phone, iphone_model,
                           iphone_year, case_color, consent, gift_status)
        VALUES (:lead_id, :gift_code, 'Khach', :phone, 'iPhone 16',
                2024, 'Đen', :consent, :status)
        """
    )

    cases = [
        {"phone": "84912345678", "consent": True, "status": "NEW"},  # chưa canonical
        {"phone": "0912345678", "consent": False, "status": "NEW"},  # thiếu consent
        {"phone": "0912345678", "consent": True, "status": "KHONG_CO"},  # status lạ
    ]

    for case in cases:
        with pytest.raises(Exception):
            with engine.begin() as conn:
                conn.execute(sql, {**base, **case})

    engine.dispose()


def test_downgrade_removes_everything(temp_database: str):
    cfg = alembic_config(temp_database)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    engine = create_engine(temp_database, future=True)
    remaining = set(inspect(engine).get_table_names())
    engine.dispose()

    assert "leads" not in remaining
    assert "audit_events" not in remaining
    assert "iphone_models" not in remaining


def test_no_pending_migration_diff(temp_database: str):
    """`alembic check`: model trong mã phải khớp migration head.

    Đây là chốt chặn để không ai sửa model mà quên viết migration.
    """
    cfg = alembic_config(temp_database)
    command.upgrade(cfg, "head")

    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - chỉ khi lệch
        pytest.fail(f"Có thay đổi schema chưa được viết thành migration:\n{exc}")
    except Exception as exc:
        # Alembic cũ có thể ném lỗi khác; báo rõ thay vì cho qua im lặng.
        pytest.fail(f"alembic check không chạy được: {type(exc).__name__}: {exc}")
